### ISSUE TITLE
Enhancement: Support for seeing "My Builds"

### ISSUE THREAD

**Issue by edbaunton** [buildbarn/bb-event-service#1]
Currently it is my understanding that bb-browser works on the level of a single operation. That is, you get a single operation id-based url back from the execution service for the operation you submitted that you can open in the browser.

For recc, it's not really going to be very usable to print out a url for every single compilation unit. Even for just failed objects (e.g. changing a header might caused N objects to fail) it could cause a lot of scrolling for the user to look at.

So what might be useful would be able to go to a "landing page" that aggregates all "my builds" or builds for a given user, this would be a high level view of the contents of the caches of builds. Knowing the user would depend on https://github.com/buildbarn/bb-storage/issues/2.

We might need a way of keying off searchable metadata, but currently much of it isn't structured. Also if two users build the same thing and hit the cache they should serve a single result to each viewer. We could probably leverage the remote execution metadata documented here https://github.com/bazelbuild/remote-apis/blob/309142d9c06ae7c1ad7da5f2bfac11c0ad468c2b/build/bazel/remote/execution/v2/remote_execution.proto#L1406

On the recc side, for example, we might consider generating a "project id" upon bootstrapping e.g. a CMake project, with recc so that we can create the concept of a "session" (and maybe use ppid to identify runs).

**Comment by t-chaik** [comment]
@EdSchouten : Is your idea to implement a Build Event Service storing the Build Event Protocol messages into a REAPI CAS and then browse the Build Event graph from the CAS data? Meaning, in Buildbarn terms: having a `bb-event-service` storing Build Event graphs in `bb-storage` that `bb-browser` would render/display?

**Comment by EdSchouten** [comment]
Hi Martin,

It's all still a pretty clean slate, so we can work this out in any direction we like. That said, some time ago I also brainstormed about this and thought about doing exactly what you proposed, but I'm not sure we can do it that way.

Unlike CAS/AC-like data, the Build Event Service is built around the idea that you want to dynamically construct build results. As soon as a build starts, you already get a URL that you can visit that shows in real time how the build progresses. It may be the case that a more traditional (SQL?)-database-like approach may be a better fit.

Alternatively, we could have something in between: for builds that are in progress, you're viewing data that is stored in-memory in the Build Event Service. Once the full build finishes, it writes it into persistent (AC/CAS-based?) storage.

The idea will of course be to let any web page as part of this project point to bb-storage where applicable (to access raw logs, inspect build failures, etc.).

**Comment by t-chaik** [comment]
Thanks for sharing your thoughts @EdSchouten!

I guess the received `BuildEvent` messages could be stored in CAS on the fly but an external client wouldn't be able to browse its children without querying an index somewhere mapping `BuildEventId` to corresponding `BuildEvent` location/digest in CAS, right? So yes, agreed, CAS only isn't a solution. 

First solution (database like approach) would work of course. What do you have in mind for the second solution: store the entire `BuildEvent` graph in memory and store it to CAS once complete? 

Pushing further the above idea of storing `BuildEvent` messages in CAS on the fly, a possible design could be to have some kind of `BuildEvent` cache that would keep in memory the `BuildEventId`-to-`BuildEvent`-digest map and persist it to CAS once complete. That kind persistence mechanism could probably be reuse in order to implement presistence for other maps like the `ActionCache`. CAS data + that mapping should allow `bb-browser` to serve URL of the form `http://.../build_event/${instance}/${hash}/${size}/` and linking form one `BuildEvent` to another.

**Comment by t-chaik** [comment]
There is another use-case that would be nice to cover: BEP/BES works well for tools that manage the entire graph of build actions like Bazel or BuildStream. For simpler tools like RECC, that only deals with individual build actions, producing such a stream of build events is more difficult because the graph is usually manage by its calling process (that being make, ninja...).

One way of producing a browsable build reports for this kind of tools would be to have `BuildEvent`-like messages linked with parent relations instead of child relations. A simple event service would allow publishing independently these `BuildEvent`-like messages using a common static parent identifier. I'm thinking each invocation of RECC would publish a `BuildEvent` using `RequestMetadata.tool_invocation_id` as `BuildEvent.parent`. A URL of the kind `http://.../build/{tool_invocation_id}` could be made available as soon as the build starts and display the reported `BuildEvent` for that id. What do you think?

**Comment by EdSchouten** [comment]
Hi Martin,

> What do you have in mind for the second solution: store the entire `BuildEvent` graph in memory and store it to CAS once complete?

Yes, exactly. But what I'd do is likely not store all of the BuildEvent objects in the CAS individually. In the common case people want to open up a page that shows most (or many?) of the build events in one go. Loading all of those from the CAS individually would be costly. I guess it would make sense to store all records in one blob. The most logical format for that would be to use the same format as what `bazel build --build_event_binary_file=...` emits, which is nothing more than a sequence of BuildEvent messages ([Go parser](https://github.com/matttproud/golang_protobuf_extensions)).

> For simpler tools like RECC, that only deals with individual build actions, producing such a stream of build events is more difficult because the graph is usually manage by its calling process (that being make, ninja...).

I remember taking part in a discussion at the Build Event/FOSDEM (together with @edbaunton?) that it may at some point be wise to split up recc into a C compiler frontend and a client daemon that runs in the background, for the purpose of improving reliability and performance. If such a decomposition is performed, the BEP/BES could be used without modification, right?

**Comment by EdSchouten** [comment]
I'm experimenting with displaying build event streams in bb-browser in this branch:

https://github.com/buildbarn/bb-browser/compare/build-events

**Comment by EdSchouten** [comment]
Considering that this issue was filed before the existence of bb-event-service and the original request of getting more insight in combined actions has in a conceptual way been satisfied, I'm going to close this issue in favour of ones that are more specific to the current implementation.

Feel free to file bugs for any specific issues you run into. Thanks!
